### PR TITLE
Implementation of the Cross Domain Adaptive Clustering(Domain Adaptation)

### PR DESCRIPTION
**Pull request by shreejalt**
Hi, 
Thanks for your excellent repository for different DA/SSL/DG algorithms. I found the CDAC paper very interesting, and I have implemented the paper in your repo and would like to merge it with your main Dassl repository. 

Link to the paper: [Link](https://arxiv.org/pdf/2104.09415.pdf)
The original implementation by the authors can be found from this link: [Link](https://github.com/lijichang/CVPR2021-SSDA)

Citing the original paper. 
```
@InProceedings{li2021cross,
    author    = {Li, Jichang and Li, Guanbin and Shi, Yemin and Yu, Yizhou},
    title     = {Cross-Domain Adaptive Clustering for Semi-Supervised Domain Adaptation},
    booktitle = {Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)},
    month     = {June},
    year      = {2021},
    pages     = {2505-2514}
}
```

### CODE REVIEW

**Comment by KaiyangZhou** [comment]
Thanks very much! Your implementation looks clean.

Is it a CVPR'19 or CVPR'21 paper? The update in the readme file puts CVPR'19 by the way.

Also, is this re-implementation tested? Do you have any numbers on the two datasets?

**Comment by shreejalt** [comment]
Hi, 
Sorry from my side, I will edit it to CVPR'21. Yes, I have tested the implementation. I have the numbers on the digit5 dataset

**Comment by shreejalt** [comment]
Hi @KaiyangZhou ,
Any updates regarding the PR?

**Comment by shreejalt** [comment]
Hi @KaiyangZhou 
There is a small bug in the scheduler function that I just checked

Can I correct it and the you can again merge?

**Pull request merged**
